@base_url = http://localhost:3000
@authToken = {{authenticate.response.body.token}}

# @name create_account
POST {{base_url}}/api/user
Content-Type: application/json

{
  "name": "Ana",
  "email": "jonas.mascarenhas@gmail.com",
  "password": "Senha@123"
}

###

# @name authenticate

POST {{base_url}}/api/auth/session
Content-Type: application/json

{
  "login": "jonas.mascarenhas@gmail.com",
  "password": "Senha@123"
}

###

 # @name createProductV1
POST {{base_url}}/api/product
Content-Type: application/json
Authorization: Bearer {{authToken}}

 {
  "name": "novo produto 22",
  "price": 1000,
  "color": "nova outra cor",
  "brand": "xaiomi",
  "model": "xaiomi 9"
 }

###

 # @name createProductV2

POST {{base_url}}/api/product
Content-Type: application/json

 {
  "name": "novo produto 2",
  "details": {
    "brand": "motorola",
    "model": "motorola XYZ",
    "color": "verde"
  },
  "price": 2000
 }

###

 # @name createProductV3

POST {{base_url}}/api/product
Content-Type: application/json

[
  {
    "name": "novo produto 2",
    "brand": "xaiomi",
    "model": "xaiomi 9",
    "data": [
        {
        "price":  1000,
        "color": "nova cor"
        },
      {
        "price":  10000,
        "color": "blue"
        }
      ]
  },
  {
    "name": "novo produto 4",
    "brand": "iphone",
    "model": "XPTO",
    "data": [
      {
        "price": 4000,
        "color": "preto"
      }
    ]
  }
]

###

# @name createProductInvalidFormat

POST {{base_url}}/api/product
Content-Type: application/json

###

# @name updateProduct

PUT {{base_url}}/api/product/24
Content-Type: application/json

{
  "name": "De novo pra garantir",
  "price": 1000,
  "color": "cor diferente",
  "brand": "marca nova",
  "model": "modelo XPTO 14"
}

###

# @name deleteProduct

DELETE {{base_url}}/api/product/21
Content-Type: application/json

###

# @name getProduct

GET {{base_url}}/api/product/23
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name findAllProducts

GET {{base_url}}/api/product/
Content-Type: application/json
Authorization: Bearer {{authToken}}


